### ISSUE TITLE
Short datatype used for Enums

### ISSUE THREAD

**Issue by calumchisholm** [mikependon/RepoDB#107]
Hi @mikependon,
Reading through the code, I noticed that the `Conjunction`, `Operation` and `Order` enums are all defined as `shorts`, and I'm puzzled about why this is - presumably it's to reduce memory usage at runtime, but in that case why not use `byte` (or `ushort`)? I suspect that values smaller than `int` are padded and aligned to a 32-bit boundary anyway, so I'm not sure this actually makes much difference in practice.

This in itself isn't a big problem, but I wonder if there's maybe an alternative optimisation available in this area? If these enum types were instead defined as `int` (as is the default), and each of their values declared as a pre-determined hash value (or at least, something random-ish, non-consecutive and non-colliding), then there would be no need to call `GetHashCode()` on these any of these types at runtime - you could simply use the enum's underlying value instead - effectively a no-op.

I haven't tested or benchmarked this, and don't know the codebase well enough to judge whether this approach would provide any meaningful gains. It may be worth considering though, particularly if the hashes are calculated within any performance-critical code paths.

It's also possible that the compiler is already smart enough to pre-calculate the hash values at build time - again, some digging would be required to confirm whether this is the case.

**Comment by mikependon** [comment]
Hmmmm! The reason why I put it as short is that because it really decrease the number of bytes when saving the data in the memory (I was into smallint before as well), just to make maximize the bytes usage and saved. However, I just researched that data type int is the default type CPU register width which means that there will be no additional cast and conversion when the compiler uses it. This really make sense! So the performance evaluation on here is that, it could improve a little the performance but could increase the memory usage a little.

With regards to the ‘GetHashCode()’ to these enum types, I am not really sure. But I agree that it is advisable to asign a constant value here (though I know it is auto-assigned by the compiler, and that would solve the value in constant). This will not give much more gains, I supposed.

Btw, in the first part of your comment here, these enum types are part of the objects QueryField, QueryGroup which I also overriden their ‘GetHashCode()’ method to override the runtime equality comparers for normal objects, lists, and IEquatable. And if you think, making it ‘int’ and assigning a default values to it would improve it, then, can I request you do the PR for this?

Once you do the PR, I will then check how the memory usage behave by running the bencher right after.

**Comment by mikependon** [comment]
Will be a part of the release greater than v1.8.4.

**Comment by mikependon** [comment]
Deployed at v1.9.0-beta1.
