### ISSUE TITLE
attribute for ignore

### ISSUE THREAD

**Issue by fake-fur** [mikependon/RepoDB#420]
hi mike

is it possible to have an attribute that tells the ORM to ignore this field when reading / writing to the database? i find myself with a model that has 2 extra fields that come from an API that do not exist in the database, so i have to make 2 versions of the model - would be great to be able to mark a column as [DBIgnore] or something

**Comment by mikependon** [comment]
There were `[Ignore]` property in RepoDb historically, but I already removed that due to the fact that the library has evolved a lot to become more intelligent. I would assume by now that RepoDb knows your schema and it will ignore the extra fields from your models when you do call both the push/pull operations.

**Comment by fake-fur** [comment]
mike 

wow this works great - better than i hoped - thanks for the effort :)

**Comment by mikependon** [comment]
This feature has been removed at v1.8.0 and can be seen [here](http://repodb.net/release/core#repodb-v180). On your behalf, please revert to me if my statement on previous comment is not reflecting as it should.

**Comment by mikependon** [comment]
@fake-fur - I just replied, and thanks for confirming.
