### ISSUE TITLE
Bug: [SQL Server 2019] RepoDb truncates strings of "Text" types

### ISSUE THREAD

**Issue by GeeWee** [mikependon/RepoDB#444]
This is a bit of an odd bug. I have the following entity, and the following tables (some stuff omitted)
```sql
CREATE TABLE [dbo].[MyEntity]
(
-- Some other columns as well, but the text column is the one that breaks
    [ExtendedAttributes] [text] COLLATE SQL_Latin1_General_CP1_CI_AS        NULL,                                           
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

When I try to insert something where the "ExtendedAttributes" text is longer than 16 characters, it's always truncated to 16 characters.

Reproducible example
```csharp
// Entity, some stuff omitted
public class MyEntity
{
    public string ExtendedAttributes { get; set; };
    public int ID { get; set; }
}

// Test case
var entity = new MyEntity(id: 5, extendedAttributes: "123456789-123456789")
await using var connection = new SqlConnection("someConnectionString");
await connection.EnsureOpenAsync();
await connection.InsertAsync(entity);
var retrieved = await connection.QueryAllAsync<MyEntity>();
retrieved.First().Should().BeEquivalentTo(entity);
```
This results in the following error:
```
Expected member ExtendedAttributes to be 
"123456789-123456789" with a length of 19, but 
"123456789-123456" has a length of 16, differs near "6" (index 15).
```

I have checked that the value is also truncated in the database, so the issue is on the insertion part not the retrieval.
I have also done the following other steps to get more info:

- I have changed the text column to a varchar(255) - this makes it work
- I have put in a Trace. The arguments in the trace are the "correct" ones
- I have tried inserting it manually via the SqlConnection (without RepoDb) and it inserts it properly. I assume this means it's not a bug in the SQL Driver.

# Potential reason
When debugging, I noticed that in `InsertAsyncInternalBase`, that the `InsertExecutionContext.InputFields.ExtendedAttributes` has the size set to 16, which is also what the string is truncated to. I don't know enough about the RepoDb codebase to understand if this is the real issue, but it seems like a promising start.

**Comment by mikependon** [comment]
@GeeWee - if you use the code below, you will see that the `TEXT` data type is of size `16` always.

```csharp
using (var connection = new SqlConnection(ConnectionString))
{
	var dbFields = DbFieldCache.Get(connection,
		ClassMappedNameCache.Get<MyEntity>(),
		null);
	dbFields
		.AsList()
		.ForEach(df => Console.WriteLine($"{df.Name} : {df.Size}")); // TEXT = 16
}
```

That is because of this [query](https://github.com/mikependon/RepoDb/blob/51937efbe152d41cc0a8f8425b47d4e0ecc525f7/RepoDb.SqlServer/RepoDb.SqlServer/DbHelpers/SqlServerDbHelper.cs#L50) at DB Helper for SQL Server.

Though it seems to be correct base on the row's pointer as explained below.

![image](https://user-images.githubusercontent.com/591015/82656302-cfa97880-9c23-11ea-9bec-9033c8c52b6b.png)

But the size extracted is not reflecting the correct length of the `TEXT` and `NTEXT` data types.

The link of the page can be found [here](https://sqlhints.com/2016/05/11/differences-between-sql-server-text-and-varcharmax-data-type/).

**To fix this:**

I need to issue a hot-fix for the query I wrote at the DB helper or you can override it temporarily using your customized Db Helper class (until the fix is given).

Internally, we are not using the `TEXT` data type, at most time we used the `NVACHAR(MAX)`. That will fix your issue as well.

**Comment by mikependon** [comment]
Please inject the file inside the attached zipped file into your code.

```csharp
DbHelperMapper.Add<SqlConnection>(new CustomSqlServerDbHelper(), true);
```

[CustomSqlServerDbHelper.zip](https://github.com/mikependon/RepoDb/files/4667819/CustomSqlServerDbHelper.zip)

Make sure to call it right after calling the `SqlServerBootstrap.Initialize()` method.

**Comment by GeeWee** [comment]
This works - however when calling it, it only works for some tests. ( I override from the same base class, and call it there ) - I can confirm that override is called, but for the same code it only sometimes calls the new CustomHelper. It's probably not worth debugging - I assume this won't be an issue if the fix is merged into the trunk.

**Comment by mikependon** [comment]
That's because RepoDb is calling the `DbFieldCache` class, in which it only calls and touches your DB once. After that, the cached `DbField(s)` pertaining to your entity is reused all throughout the lifetime of your application.

**Comment by mikependon** [comment]
The fix is now available at RepoDb.SqlServer >= v1.0.9.

**Comment by GeeWee** [comment]
I can confirm that the fix works.
