### ISSUE TITLE
Question: How to create SQLite database and tables if not exists?

### ISSUE THREAD

**Issue by etheaven** [mikependon/RepoDB#449]
Missing this in [the tutorial](http://repodb.net/tutorial/get-started-sqlite)  
Mind helping?

**Comment by mikependon** [comment]
Thinking that SQLite DB creation must be covered by SQLite [documentation](https://sqlite.org/docs.html). You can see it [here](https://sqlite.org/quickstart.html).

Trying to avoid rewriting it as it is completely out of context for this library. But in anyway, we will assess (whether) to add this into our documentation.

**Comment by etheaven** [comment]
What about the tables creation? Do you have to create SQL query to insert tables if they do not exist or is there a way where this library generates that for you?

**Comment by mikependon** [comment]
@etheaven - thank you for asking. There is no code first support for RepoDb and TBH we will never support such feature as we are heading towards different path. You have to create the tables yourself in all DB providers.

P.S: We are not implementing things that already exists in EF, we highly recommend you use EF for your DB migration (or any other DB migration tool). I can recommend some if you would like, otherwise, please just use EF.

**Comment by etheaven** [comment]
Okay thank you very much.
