### ISSUE TITLE
Question: Set Cache on Update (to modify cached object)

### ISSUE THREAD

**Issue by gtejeda** [mikependon/RepoDB#460]
First, apologies, this is a question, not an issue... didn't find anything on SO and hoped any of you could give me a quick hint on the topic.

I LOOOOOOVE the idea of your integrated memory caching, I've been doing it manually for a while now, but your implementation would make my life a lot easier to be honest, but I wanted to ask, what happens if I have an object in memory and it's modified after cached, can I destroy the cache in those cases to avoid old data being retrieve from cache?

Thanks and again apologies for the question,
Keep up the good work!

**Comment by mikependon** [comment]
Thank you and no need fo an apology. This is OSS and you are in the right place to ask about this.

The answer to your question is, the cached item will not be updated until the 180 minutes has elapsed (since this cache item has been created).

**Some advice below:**
- Do not cache the non-static tables, only those that are rarely or not really changing
- You can always define the expiration in minutes
- If you have the reference to your ICache, you can remove the cache item by calling the Remove method. It will be updated fresh from DB on the next call
- If you have the reference to CacheItem, expire that cache by setting the Expiration property to an ealier date

Hope this helps!

**Comment by gtejeda** [comment]
Mike,
with this question you guys officially become my #1 favorite OSS project! :D 

I can definitely use it for the slow-changing data I have, and today I begin the implementation.
After that I may try manual removal (it's what I'm doing now anyway)...

Thanks thanks thanks!
Geo

**Comment by mikependon** [comment]
@gtejeda - thank you for your comments. In anyway, that was 2 years ago. There were so many optimization happens along the way and the new primary key identification is now placed in the [PrimaryResolver](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb/Resolvers/PrimaryResolver.cs), in which also considered the [FluentMapper](https://repodb.net/feature/implicitmapping) features. It becomes more cleaner and easier for the community to read and follow the code (in case of PR). In anyway, I hope you enjoy using this library.

**Comment by mikependon** [comment]
Oopps! It seems I received it wrongly due to the pointer in the first issue we had. In anyway, thanks! Hopefully, we answered you in a write manner and in timely fashion. :)

By the way, I already added a [to-do](https://github.com/mikependon/RepoDb.NET/issues/3) task on our site to further elaborate the caching documentation.

Please remember that you should create your own `ICache` object if you are using direct calls to the `IDbConnection`. But if you are using a repository, then it is automatically created internally (if you passed nothing to the `cache` argument).

**Comment by gtejeda** [comment]
Thanks again @mikependon all of these comments will definitely help me out, specially since I'm starting with a repository to try things out.

**Comment by mikependon** [comment]
It is my pleasure! Please refer to this [blog](https://medium.com/dev-genius/building-a-powerful-and-generic-repository-in-net-667edea193f6). At the end of the blog, you can see the following repository as gists ([EntityRepository](https://gist.github.com/mikependon/b409cc549052e2b5d77574e2b0948c3b), [SqlConnectionEntityRepository](https://gist.github.com/mikependon/d61928bd1230a41c249b72d24a24ab21)). It is a proven repository and is already working in the Production environment for various critical application.

Of course, some tracing and caching implementations were implemented on the deriving repositories, but this base is quite good already.

**Comment by mikependon** [comment]
I am closing this issue now. Please feel free to reopen if you think this is not yet done and/or completed.
