### ISSUE TITLE
Enhancement: Support commandTimeout parameter in Bulk Operations

### ISSUE THREAD

**Issue by callumwyq** [mikependon/RepoDB#466]
I encountered timeout exception in bulk operations (Insert, Update, Merge, Delete), even though I had specified **bulkCopyTimeout** parameter to few minutes/hours.

After go through the source code, I notice the bulk operations actually calling connection.Execute...() internally, which may cause timeout exception after default timeout 30 secs.

Suggest to add **commandTimeout** parameter in bulk operations.

Thanks in advance!

**Comment by mikependon** [comment]
Great findings! Thank you for this report. This is quietly hard to catch in Integration Test. I am happy to fix this one for you. When do you need the fix for this?

There are lot of internal calls to the execute, but as I can see it, the fix should happen on the calls to Pseudo Temporary Table into the Actual Table. See the code [here](https://github.com/mikependon/RepoDb/blob/cde2e7712be22d7b6f268e89c32d54c6d209450a/RepoDb.Extensions/RepoDb.SqlServer.BulkOperations/RepoDb.SqlServer.BulkOperations/System.Data.SqlClient/SqlConnection/BulkInsert.cs#L1784) and [here](https://github.com/mikependon/RepoDb/blob/cde2e7712be22d7b6f268e89c32d54c6d209450a/RepoDb.Extensions/RepoDb.SqlServer.BulkOperations/RepoDb.SqlServer.BulkOperations/System.Data.SqlClient/SqlConnection/BulkInsert.cs#L1796).

In such call, the timeout parameter must be passed like below.

```csharp
result = await connection.ExecuteNonQueryAsync(sql, commandTimeout: bulkCopyTimeout, transaction: transaction);
```

**Comment by callumwyq** [comment]
Glad to hear that! I hope this enhancement can be done as soon as possible, as I need it urgently for production migration in couple days. But of course if you cant make it, then i will clone and modify my own temporarily.

**Comment by mikependon** [comment]
The code changes are minor but it is not covered by the Integration Tests due to the fact that I could not freeze the tests.
I had issued a beta release for you at [RepoDb.SqlServer.BulkOperations v1.0.12-beta1](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.0.12-beta1).

Kindly upgrade your copy by simply installing the following version with the command below.

```
> Install-Package RepoDb.SqlServer.BulkOperations -version 1.0.12-beta1
```

**Comment by mikependon** [comment]
@callumwyq , the fix is now available on the latest release. I am closing this issue now. Please revert anytime if you still have questions. Thanks
