### ISSUE TITLE
Question on SQL Server computed column

### ISSUE THREAD

**Issue by fenilrathod** [mikependon/RepoDB#494]
Are SQL Server computed columns supported during update and insert operations?

I have a table with one computed column which is getting error while insert and update operation using BaseRepository with defined model.

I've found 'Ignore' attribute was there earlier but now RepoDb intelligently maps columns and properties based on schema.
Is it considering computed columns during mapping and is there any other workaround to support computed columns?

**Comment by mikependon** [comment]
Though most data types are supported by the library, but TBH, we never tested it yet with the computed columns. I have an impression that it will only works on GET operation (i.e.: Query, QueryAll, etc), and not on the PUSH operations (i.e.: Insert, Update, Merge, etc). I am afraid to say that this is a limitation unless otherwise we recur the implementation of the `IgnoreAttribute`.

Anyway, for us to debug it easily, would you be able to share the table and your class? If not, an identical schema or class would do for us.

Alternative way, only on that table, is to make a non-typed targeted approach like below.

```csharp
using (var connection = new SqlConnection(ConnectionString))
{
	var model = new // Just a dynamic object
	{
		Column1 = "Column1 Value",
		Column2 = "Column2 Value",
		// ComputedColumn = "ComputedColumn Value" // Comment this
	};
	var id = await connection.InsertAsync("[dbo].[TableName]", model);
}
```

**Comment by fenilrathod** [comment]
Yes non-typed would work fine.
I've taken another approach to use exiting typed generic repository and to avoid writing dynamic objects.

Basically created two classes for given table. one having properties excluding computed columns. second having properties for only computed column inherited by first class. And mapping of second class to correct table.

This is working fine. I only need to instantiate repositories for particular classes based upon GET or PUSH operations. 

Moreover, I will share sample code in some time.
Thanks!

**Comment by mikependon** [comment]
@fenilrathod - having 2 models is an alternative way, for as long you're okay to manage that. Use the one with computed columns in your GET and the other one in your PUSH operations.

I will put this scenario as part of the limitations of the library (for now). Please feel free to close if your issue is solved.
