### ISSUE TITLE
Bug: QueryAsync with empty QueryField list throws SQL exception

### ISSUE THREAD

**Issue by asleire** [mikependon/RepoDB#498]
Currently using `RepoDb.SqlServer` `1.0.13`

The code `db.QueryAsync<SettingTagDbo>(Enumerable.Empty<QueryField>())` generates the following invalid SQL
`SELECT [SettingDefinitionSet], [SettingCollection], [SettingCollectionValue], [ResourceType], [ResourceId], [Path], [SettingType], [TagType], [Value] FROM [SettingTag] WHERE () ;`

I would expect `QueryAsync` with an empty QueryField list to be equivalent to `QueryAllAsync`

This appears to be a similar yet different error than in https://github.com/mikependon/RepoDb/issues/463

Current workaround is similar, call `QueryAllAsync` or `QueryAsync` depending on whether QueryField list is empty

**Comment by mikependon** [comment]
Thanks for this and it is acknowledge. I will do fix this. It is actually working if you're to use the 'whereOrPrimaryKey' passing the nulls.

```csharp
var data = await connection.QueryAsync<SettingTagDbo>(whereOrPrimaryKey: null);
```

You are correct, it should behave like `QueryAllAsync`.

**Comment by mikependon** [comment]
I hope you are not block by this for now. Thanks

**Comment by asleire** [comment]
No rush, the workaround is simple :)

**Comment by mikependon** [comment]
The fix is simple as well, see [here](https://github.com/mikependon/RepoDb/blob/c0df2e00b67cfdf7f6eed174667a5cee9a706299/RepoDb.Core/RepoDb/QueryBuilder.cs#L807). Instead of 'null-checks', we can do the 'presence-check' like `queryGroups?.Any() == true` somewhere.

EDIT: The fix seems to be checking of the `QueryField` object inside that `QueryGroup` object.

**Comment by mikependon** [comment]
Closing this ticket now. Kindly let us know if you have any questions. Thanks!
