### ISSUE TITLE
Request: Proposal for result returning

### ISSUE THREAD

**Issue by alper-atay** [mikependon/RepoDB#554]
Hi, i think need return proposals some operations.

We have
`TResult result = dbConnection.Insert<TEntity, TResult>(...);`

Don't have

`IEnumerable<TResult> insertedEntities = dbConnection.InsertAll<TEntity, TResult>(entities);`
`TResult updatedEntity = dbConnection.Update<TEntity, TResult>(entity);`
`IEnumerable<TResult> updatedEntities = dbConnection.UpdateAll<TEntity, TResult>(entities);`

Update and UpdateAll always return affected row count. But we dont know, which rows changed. 

For example

`int updatedCount = await dbConnection.UpdateAsync(SourceModel, queryGroup, fields, Hints, CommandTimeout, Transaction, Trace, StatementBuilder);`

So we have a problem. Rows changed by queryGroup and we dont know which row changed. If find succeed, changes override SourceModel. In the update description =>  Updates an existing row in the table. It updates the first row it finds.

If, we have like that

`TModel updatedModelOnFirstFind dbConnection.UpdateAsync<TModel, TModel>(SourceModel, queryGroup, fields, ...);`

Why we need that. SourceModel is a class (ref type). I dont want to change on operation. Add to option with as secondary generic pass like InsertAsync and MergeAsync. 

```
class User {
  public int Id { get; set; }
  public int Name { get; set; }

  IEnumerable<User> UpdateAll<User>(IDbConnection dbConnection, IEnumerable<User> users) 
  {
    // A
    int updatedUserCount = dbConnection.UpdateAll(users);
    // B
    IEnumerable<User> updatedUsers = dbConnection.UpdateAll<User, User>(users);
  }
}
```

Case 1:
Maybe some models deleted in database before operation. A operation update on found rows and changed data override to found models. B operation update on found rows and changed row stacking in a collection and return as IEnumerable.

Case 2:
Maybe some models have wrong Ids. So A operation don't undestand which models updated. We need to query by Ids. B operation correctly return updated rows.

The aim is to access the results directly without doing a query.

Disadvantage;
1) More memory and CPU usage

Advantages;
1) More convenience on operated rows.

**Comment by mikependon** [comment]
@alper-atay - this has been religiously discussed and thought (internally). The [Insert](https://repodb.net/operation/insert) operation for example, we are returning the primary/identity key value (etc) instead of the entity model itself; same goes for [Update](https://repodb.net/operation/update), [Merge](https://repodb.net/operation/merge) and all their corresponding [Batch Operations](https://repodb.net/feature/batchoperations).

I will be frank with you now, this will affect the core design of the library, even with the [Bulk Operations](https://repodb.net/feature/bulkoperations). We had already decided not to choose this path, but rather had choosen the other side of the use-cases, and that is to return the affected primary/identity keys over returning the entity model. The affected rows primary/identity key will be automatically set back to the model, and/or you can get the reference anywhere from the models. The decision of the architecture is not documented, but is collectively been decided.

Though TBH, it is not that difficult to switch, the memory-efficiency and the performance is also not a problem as RepoDB is quite optimize there, but it is a bit tedious to update all the Integration Tests and Unit Tests affected by this request. I would say, it would be a massive updates that could affect few thousand of those Test Suites. In addition to that, I am afraid that this would trigger a conflict to other consumers of the library, in which I am very careful TBH. I, as an author, personally not to push this rather than receiving the critics we are not expecting. My cents!

Hope you understand.

**Comment by alper-atay** [comment]
I understand very well that RepoDb is the most useful ORM and you want to protect it. I've tried a few alternatives and I think RepoDb is the most logical solution.

I would like to add something without making big changes. Certainly it takes time. I'm pretty busy nowadays. First of all, after I finish my own project, I will take responsibility on this issue. 

Thanks.

**Comment by mikependon** [comment]
TBH, I am tracking you and your project is doing well. I will try to see if I can contribute there, please do let me finish the stuffs of `F#` request and finalizing some adhoc updates on the compiler first. I am happy if I can contribute on your project, and hopefully you to RepoDB as well in the near future.

Speaking of your project, can you try create README so it is visible to the possible consumers? Also, please do let me know if I can start speaking of it to the possible library consumers of RepoDB.

**Comment by mikependon** [comment]
We will not fix this request, please feel free to revert. Thanks
