### ISSUE TITLE
Question: Static FluentMapper Class inside ASP.NET Application

### ISSUE THREAD

**Issue by JanBrandenburger-LSF** [mikependon/RepoDB#822]
Hello,
I have a question and hope to get a hint.
 
I have created an application that is based on ASP.NET. For this I use the technology WiseJ.
 
Now I have implemented RepoDB there and locally everything works perfect.
 
The problem I have is about FluentMapper, which is implemented as a static class.
 
I call the initialization of the SQL bootstrapper when I start the application and then in the next step the FluentMapping methods of my custom mappings. ( https://repodb.net/mapper/fluentmapper)
 
The first user that calls the application on IIS can work normally.
 
Every following user gets a RepoDb.MapperExists exception.
 
This behavior in my opinion is because the class is static and thus the mappers are available to all instances within the IIS application pool. Whether this is "good" or not, I can't assess.
 
Have I implemented something incorrectly here or does anyone have a solution so that the error does not occur? Maybe there is a sample how to use FluentMapper inside a MVC-Application.
 
I contacted WiseJ support and they warned against static classes in WebApps as they are not threadsafe.
 
I thank you for any ideas and hints.
 
Please give feedback if I made the question unclear or more information is needed.
 
Thanks.
 
Regards
Jan

**Comment by mikependon** [comment]
@JanBrandenburger-LSF - first, thanks for filing this question. I personally never thought that Static classes effect on the IIS. But in anyway, there is an additional argument named `force` in which you can pass to somehow solve this mapping exists exception, atleast for this scenario.

Would you be able to do this and check if that solves your problem?

![image](https://user-images.githubusercontent.com/591015/117274231-2a4fda80-ae5d-11eb-9510-b2217fffd7d8.png)

Note: This force argument is existing to all the entity mapping definition methods.

**Comment by JanBrandenburger-LSF** [comment]
@mikependon 
Hello,
thank you for your quick reply and time you took.

Here is an excerpt from the two consultants:

********************
Hi Jan,

You're correct, static variables are available across all different user sessions in your app pool. You can specifically access session-based objects by using the Application.Session dynamic object (i.e. Application.Session.myObject = "something").

Static variables will not be reset until all instances of the application are closed and the IIS app pool restarts, IIS crashes, or the server is rebooted. If you close all sessions and immediately open up a new one, the static value will be retained.

************************

I asked also, if this is an WiseJ problem.

Answer:

*******************

It's not a Wisej issue. Statics are statics in any system.

You can use statics in a web app but you have to be careful that access is thread safe and then they don't store "instance" values that are supposed to be for only one user.

*******************

I already found the force method, but it is "dirty" at first sight if every new user overwrites all other users mappings again.

I don't know if there are developers here who have already worked with the FluentMappers on MVC....
Maybe I am doing something wrong.

Thanks for all,

Best,
Jan

**Comment by mikependon** [comment]
> I already found the force method, but it is "dirty" at first sight if every new user overwrites all other users mappings again.

This should not be a culprit in your case, unless each user of the web application has different mappings. I would assume they're using the same mapping you initially defined when calling the static FluentMapper class. **Or, correct me here.**

Another thing is, since the static class is shared and is being retained even after the session is closed (as mentioned above), I would suggest that you call the FluentMapper class methods inside your customized static class (or singleton registrations) and not on the instance level class. This is just to ensure that you are only calling the FluenhtMapper methods once. However, this is not true if each user has its own different mapping.

**Comment by JanBrandenburger-LSF** [comment]
Hi,
Your are right, the settings are always the same.

I'm thinking about how to encapsulate the class.

Additionally, if there are users here who have experience with MVC and Fluent Mapper, I appreciate any feedback.

**Comment by mikependon** [comment]
Since your problem is the repetitive calls based on the newly visitor of the site, then just wrapping it within your customized static class or within your singleton class (registration) would eliminate such issue. I will tag this as "Needs Collaboration" so any visitor could share their experiences pertaining to this case.

**Comment by JanBrandenburger-LSF** [comment]
Thank you very much!
Jan
