### ISSUE TITLE
PK violation during bulkupdateasync

### ISSUE THREAD

**Issue by vilijatr** [mikependon/RepoDB#869]
I am testing insert / update / delete operations in the database. Insert / delete works but for bulkupdateasync I am getting a violation of the PK error. 
I start testing by truncating a table. Then I use bulkinsertasync and that goes well. Afterwards I use the same table to update and this is when I get the error.
The table does not have an identity but rather a composite primary key which is defined in the context
![image](https://user-images.githubusercontent.com/20964843/132323187-170d1022-84e0-4833-a198-d3d7c6cef8c8.png)
The error is a classical one:
Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 
It is solved by adding qualifiers in the operation:
![image](https://user-images.githubusercontent.com/20964843/132323454-e634d03f-354c-4367-902a-0ef32981b88d.png)

**Comment by mikependon** [comment]
Hi @vilijatr - it is very unfortunate, we cannot replicate this issue. Glad if you can help us create a small project solution that replicate this issue.

**Comment by mikependon** [comment]
@vilijatr - RepoDB does not support composite key by default. It can be remedy by defining a qualifiers.

The other issue you mentioned in relation to the exception that is being thrown on BulkUpdateAsync cannot be replicated by us. Maybe you have other scenario that we have missed. Is this still a problem in your side? Otherwise, we will not do anything here and probably close the case without any action.

Or, would you be able to provide a small project that replicates this?

**Comment by mikependon** [comment]
Closing this issue now.
