### ISSUE TITLE
Hello !! I have a question about cache.

### ISSUE THREAD

**Issue by seongguk92** [mikependon/RepoDb#959]
https://repodb.net/feature/caching
example
~~~
var cache = CacheFactory.GetMemoryCache();
using (var connection = new SqlConnection(connectionString))
{
    var expirationInMinutes = 60 * 24; // 1 day
    var products = connection.QueryAll<Product>(cacheKey: "products",
        cacheItemExpiration: expirationInMinutes, cache: cache);
}
~~~
cacheItemExpiration: expirationInMinutes(minutes)
-> Is there a way to put it in seconds? ㅠ_ ㅠ

**Comment by mikependon** [comment]
@seongguk2i - no, purposely it has been decided in the past to be in minutes. Intriguing, why cache for few seconds? Can you share some words on your use-case?

**Comment by seongguk92** [comment]
@mikependon 
I'm trying to make an api with data that changes in real time, but many users can access it.
10 seconds of caching is required.

Is there any way?
I am using repodb very well now.

It would be great if it could be done in seconds. ㅠ_ ㅠ

**Comment by mikependon** [comment]
It is a very simple change, but it is a breaking change to the other users. Since we are trying our best not to create a breaking change, this request will never happen in the future.

But, you can actually control the caching by having a direct reference to the `ICache` object. Below is the way how to manually set the expiration per item.

```csharp
var cache = CacheFactory.GetMemoryCache();
var item = cache.Get<IEnumerable<Product>>("products");
item.Expiration = DateTime.UtcNow.AddSeconds(10);
```

Call this one after you called the `Query` method. Please note that the `Expiration` is always in `Utc` date.

This is also a good class to manipulate the actual cache items cached within the target `ICache` object (i.e.: Flushing, etc).

**Comment by mikependon** [comment]
In your scenario, if the data is frequently changing, then do not cache it. We also highlighted this on our documentation.

![image](https://user-images.githubusercontent.com/591015/137281501-a74fa76d-010c-4417-8e39-e168e7827a55.png)

**Comment by seongguk92** [comment]
Thanks > <
